### ISSUE TITLE
[FSB Batch Generator] 0xc00007b error

### ISSUE THREAD

**Issue by Seanoo1** [bartlomiejduda/Tools#12]
https://github.com/bartlomiejduda/Tools/tree/master/NEW%20Tools/FSB%20Batch%20Generator

I installed all of .dll file that require, but when I run "FSB_BATCH_GENERATOR.BAT", then up error appear.

I reinstalled all driver using aio, dxrt64 patch, run as administer. But nothing works.

**Comment by bartlomiejduda** [comment]
You don't have to install any DLLs to use this. It is only a BAT script for FMOD Designer.
So you need to get a copy of FMOD Designer and then follow requirments from the readme and that's it - you can use execute script.
