### ISSUE TITLE
Problem with Disney's Up game.

### ISSUE THREAD

**Issue by emanuelect** [bartlomiejduda/Tools#14]
Hi, I wanted to upscale the textures in the game, but I can't extract them from the dpc archive. I tried downloading some Asobo .py scripts, but when I start them, they close right away. Could you please help me?

**Comment by bartlomiejduda** [comment]
Sorry, I don't really support DPC archives on this Github repositoory. I only did a quick research a long time ago and then I've stopped researching it completely.

**Comment by emanuelect** [comment]
OK, thank you anyway.
