### ISSUE TITLE
Trying to understand .idx and .bin files

### ISSUE THREAD

**Issue by DeadlyMissile** [bartlomiejduda/Tools#16]
So I extracted this .dat folder and found a single .idx file with a bunch of .bin files. I couldnt make sense of the content. Maybe they are encrypted or compressed? I would appreciate your help here!

Attached some samples:
https://file.io/JGvaizmsfbRb

**Comment by bartlomiejduda** [comment]
Both of these files seem to be encrypted. What game they are from?
Also how did you extract this ".dat folder"?

**Comment by DeadlyMissile** [comment]
@bartlomiejduda Thank you for replying!

> Both of these files seem to be encrypted. What game they are from?

A game called [Call of Dragons](https://callofdragons.farlightgames.com/).

> Also how did you extract this ".dat folder"?

I simply used 7zip.

Btw how did you know it was encrypted and not, like, compressed?

**Comment by bartlomiejduda** [comment]
> Btw how did you know it was encrypted and not, like, compressed?

Just an educated guess based on many file samples I've seen in the past.

> A game called [Call of Dragons](https://callofdragons.farlightgames.com/).

It is an MMO game. It's likely to have anti-debug protection, so it can be really hard to reverse engineer encryption method for your samples.

**Comment by DeadlyMissile** [comment]
So there is no hope :( ?

**Comment by bartlomiejduda** [comment]
Not from me directly. But you can always create a topic on xentax forum 
https://forum.xentax.com/index.php
hoping that someone else will be able to help.
