### ISSUE TITLE
[Request] Hana to Taiyou to Ame to (.bin) PS2

### ISSUE THREAD

**Issue by 564498dfs** [bartlomiejduda/Tools#18]
Is there any QuickBMS script for Hana to Taiyou to Ame to (Flower Sun and Rain) .bin files? Most scripts I've tried already didn't work. Thanks, https://www.mediafire.com/file/216x0cav9yu0eta/FSR_Samples.zip/file

**Comment by bartlomiejduda** [comment]
Sorry, I don't know any scripts for this game.
