### ISSUE TITLE
The Amazing Spider-Man

### ISSUE THREAD

**Issue by sinnerclown380** [bartlomiejduda/Tools#19]
The Amazing Spider-Man bms command not extracting files?

**Comment by sinnerclown380** [comment]
Can't a tool be made using this file format?

**Comment by bartlomiejduda** [comment]
No. It is not complete, so it requires some reverse engineering first.

**Comment by sinnerclown380** [comment]
Is there anyone who can?

**Comment by bartlomiejduda** [comment]
You can ask in those topics:
https://forum.xentax.com/viewtopic.php?t=9457
https://forum.xentax.com/viewtopic.php?t=25522

**Comment by sinnerclown380** [comment]
There is no one left to make a tool anymore, and there is no one who responds to the topics.
