### ISSUE TITLE
[Request] Add support for text files from gangstar series

### ISSUE THREAD

**Issue by luatsenpai** [bartlomiejduda/Tools#2]
I'm currently working with the text file of gangstar series
I found the structure of the file and sucsess to edit, but edit all of file then edit their hex length is also hard and time consuming, so i wonder could there any tool or script to easily just extract the text out, then edit the length when reimport?
Here is the sample file
Tks for help
<img src="https://i.ibb.co/McHcZVx/2.png" alt="2" border="0">
<img src="https://i.ibb.co/khtJh3C/1.png" alt="1" border="0">
sample file
[https://mega.nz/file/MKAjHQgS#iOwrKglLLb8juiaWW0YY008pnkwyzZCCkTKkBobNKkY](url)

**Comment by bartlomiejduda** [comment]
Hi, I'll check it later and let you know.
Can you tell me exact name of the game from gangster series you want to translate?

**Comment by luatsenpai** [comment]
> Hi, I'll check it later and let you know.
> Can you tell me exact name of the game from gangstar series you want to translate?

gangstar miami

**Comment by bartlomiejduda** [comment]
@luatsenpai I have created a program to automate text export and import.
https://github.com/bartlomiejduda/Tools/blob/master/NEW%20Tools/Gangstar%20Miami/Gangstar_Miami_Text_Tool.py
Please test it and let me know if it works.

**Comment by luatsenpai** [comment]
> @luatsenpai I have created a program to automate text export and import.
> https://github.com/bartlomiejduda/Tools/blob/master/NEW%20Tools/Gangstar%20Miami/Gangstar_Miami_Text_Tool.py
> Please test it and let me know if it works.

@bartlomiejduda An error occurred while importing
<img src="https://i.ibb.co/MP5GqF1/error.png" alt="error" border="0">
file modify: [https://mega.nz/file/lKhyUQya#Y_1kXH7QWubpX0Q7kEtIn4CwJe2Isua-v54uO53tnis](url)

**Comment by luatsenpai** [comment]
Btw, I try your code on termux android
<img src="https://i.ibb.co/svMB8r7/529500c1-3ab3-40e1-b391-fc88c7eaa20b.jpg" alt="529500c1-3ab3-40e1-b391-fc88c7eaa20b" border="0">
and succedded, i don't know why
and not found any error yet

**Comment by bartlomiejduda** [comment]
@luatsenpai Ok, I have updated the program. Please check now.

**Comment by luatsenpai** [comment]
> @luatsenpai Ok, I have updated the program. Please check now.

@bartlomiejduda Please excuse my late response, i tried script you fixed
and now it works
<img src="https://i.ibb.co/PmyWkz5/test.png" alt="test" border="0">
