### ISSUE TITLE
[Request] Time Hollow Nds Text tool

### ISSUE THREAD

**Issue by luatsenpai** [bartlomiejduda/Tools#20]
Hello, I'm sorry to bother you.
But can you help me write a tool so that I can easily edit the text of the Time Hollow game?
The structure of the text is also quite simple.
<img src="https://i.ibb.co/mBqwmX1/thst1.png" alt="thst1" border="0">
<img src="https://i.ibb.co/KG6xgBW/thst2.png" alt="thst2" border="0">
<img src="https://i.ibb.co/5jgWPsP/thst3.png" alt="thst3" border="0">
Sample text:
(Wow, Sox really did scratch me up good...)<kw>
[S00.zip](https://github.com/bartlomiejduda/Tools/files/12560861/S00.zip)
Thank you very much.

**Comment by YouKnow-sys** [comment]
here is a quickbms script for it
```js
idstring "\x01\x00" # why not
get COUNT SHORT

get NAME basename
STRING NAME + ".txt"

for i = 0 <= COUNT
	get OFFSET long
	slog NAME OFFSET -1
next i
```

**Comment by luatsenpai** [comment]
> here is a simple quickbms script for it
> 
> ```js
> idstring "\x01\x00" # why not
> get COUNT SHORT
> get _STRINGS_START_OFFSET LONG
> 
> get NAME BASENAME
> STRING NAME + ".txt"
> 
> for i = 0 < COUNT
> 	get OFFSET LONG
> 	slog NAME OFFSET -1
> next i
> ```

Thank you very much, it works fine and haven't encountered any errors yet
