### ISSUE TITLE
Extract from Catwoman

### ISSUE THREAD

**Issue by mopoIo** [bartlomiejduda/Tools#21]
Sorry, I know this must be super random but I'm trying to extract the 3D model of catwoman to print it to 3D since that's my girlfriend's favourite childhood game and I thought that'd be an incredible gift. I've tried using Ninja Ripper 2 to get the model from the game but the model looks really glitched and I thought what better idea than get the model straight from the game. I'm on a place where I managed to extract the VOL and AVL files, but now I'm left with a bunch of PCA, PCS and PCM files. How can I get the models from them? I'm experienced with Blender so once I have the model I know what to do, but I've been digging old forums and I can't figure it out, I was wondering if you knew? Thank you so much and sorry for the random request!

**Comment by bartlomiejduda** [comment]
Hi, sorry but I don't know how to extract 3D models. I can only recommend asking on Xentax forum.
