### ISSUE TITLE
[Request]  Alice In Wonderland (Nds) Text tool

### ISSUE THREAD

**Issue by SakiMika** [bartlomiejduda/Tools#23]
Hello, hope you have a nice day
Can you help me write a tool to easily edit the text of the game Alice in Wonderland?
This is the text structure:
<img src="https://i.ibb.co/Sy8gjPQ/struct1.png" alt="struct1" border="0">
<img src="https://i.ibb.co/TB92pVc/st2.png" alt="st2" border="0">
<img src="https://i.ibb.co/mXTvst0/st3.png" alt="st3" border="0">
<img src="https://i.ibb.co/64rtw3L/st4.png" alt="st4" border="0">
[alice.zip](https://github.com/bartlomiejduda/Tools/files/13910197/alice.zip)
Here is sample text:
Objective  complete!
Objective  Location  updated!
Thanks a lot!

**Comment by luatsenpai** [comment]
Hello, you can use autodump by melob for this game
link: http://coreline.su/#soft/

**Comment by SakiMika** [comment]
solved
