### ISSUE TITLE
[Request] Rumble Racing *.av / *.trk /*.lsc

### ISSUE THREAD

**Issue by mrmaller1905** [bartlomiejduda/Tools#29]
What is *.av / *.trk /*.lsc from Rumble Racing and can you develop a program that can unpack data with filenames?

Samples:
https://drive.google.com/file/d/1tbqwTtlAz5u3iyFMooUGw_CgADr-yjRq/view?usp=sharing

**Comment by bartlomiejduda** [comment]
No.
