### ISSUE TITLE
[Request]Zenonia4 ft2 font

### ISSUE THREAD

**Issue by fm39hz** [bartlomiejduda/Tools#3]
Could you write a tool to edit this ft2 font?
This is from zenonia4 game, i could possibly edit the text but couldn't manage to open this font
i think it is korean texture font of the game
[font.zip](https://github.com/bartlomiejduda/Tools/files/6589909/font.zip)

**Comment by bartlomiejduda** [comment]
Hi, I've checked the files. They don't seem to contain any texture data, only coordinates or something similar.
Unfortunately I'm not familiar with the game or  with the format, so I won't be able to write any tool for that, sorry.
