### ISSUE TITLE
[Request] Beyond Good and Evil - 20th Anniversary Edition (PC, PS4, PS5, Xbox One, Xbox Series X) PAK

### ISSUE THREAD

**Issue by Lilothestitch16** [bartlomiejduda/Tools#30]
Can you update the Beyond Good & Evil 20th Anniversary Edition Script and add support for PC, PS4, PS5, Xbox One, and Xbox Series X? I have samples from the PC Version.

**Comment by bartlomiejduda** [comment]
I've replied on ResHax:
https://reshax.com/topic/845-beyond-good-and-evil-20th-anniversary-edition-pak-bpak/#comment-4194
