### ISSUE TITLE
[Request] Code Lyoko: Quest for Infinity GCN, CP2, PC

### ISSUE THREAD

**Issue by Lilothestitch16** [bartlomiejduda/Tools#31]
Hi would it be possible to make a tool for extracting .gcn, .cp2, and .pc files from Code Lyoko Quest for Infinity? I want to be able to extract 3D Models and Textures from it with rigging.
[CLQFI_Samples.zip](https://github.com/user-attachments/files/16006971/CLQFI_Samples.zip)

**Comment by bartlomiejduda** [comment]
Hi. No, sorry, I don't know anything about those formats and they seem to be too hard to reverse engineer.
