### ISSUE TITLE
Help with the Persona 5 - Strikers file.

### ISSUE THREAD

**Issue by Digote** [bartlomiejduda/Tools#33]
First of all, congratulations on your help to the community. I've been following your repository.

I'd like to see if I can get some help or a path to finding a solution. The game Persona 5 - Strikers made by Koei Tecmo uses the Linkdata.idx + LinkData.bin pattern, but it seems to be in a different way. The IDX file seems to be inside the game's .exe file, and besides **compression**, there also seems to be **encryption** in the .bin file. I'll leave a tool here that worked until a few builds ago but stopped working.

Here is a pull request where someone managed to locate the key.
https://github.com/yretenai/Cethleann/pull/36

I'll also leave a link to the .exe and the LinkData.bin file:

[Game EXE](https://www.mediafire.com/file_premium/4a7br1vaf3yso0s/game.zip/file)

[LinkData.bin](https://www.mediafire.com/file_premium/jqagmlk38v87etb/LINKDATA.zip/file)

Thanks

**Comment by bartlomiejduda** [comment]
Hi.

> congratulations on your help to the community

Thanks ;3

> The IDX file seems to be inside the game's .exe file, and besides compression, there also seems to be encryption in the .bin file.

I've never really worked too much on reverse engineering Koei Tecmo formats.
The're still a mystery to me, so I'm unable to support extraction from BIN/IDX without serious RE work like debugging the game etc.

You should ask about it on ResHax forum https://reshax.com/ and on resHax discord server.
Maybe someone else will be able to help with this case.
