### ISSUE TITLE
[Request] Tom Clancy's Splinter Cell Conviction Mobile Text Support

### ISSUE THREAD

**Issue by SakiMika** [bartlomiejduda/Tools#6]
Hello there
I'm sorry to disturb you
I want to translate Tom Clancy's Splinter Cell Conviction Mobile to my language
But i have a little problem
The text file of the above game includes 2 files
*.off is offset (pointer)
*.bin is text
Here is structure of the file
<img src="https://i.ibb.co/kBBcrsP/20210731-184608.jpg" alt="20210731-184608" border="0">
<img src="https://i.ibb.co/HqgHbWy/20210731-184100.jpg" alt="20210731-184100" border="0">
<img src="https://i.ibb.co/T8mtVkV/20210731-183919.jpg" alt="20210731-183919" border="0">
<img src="https://i.ibb.co/NLNmpSk/20210731-183954.jpg" alt="20210731-183954" border="0">
I also send the file in attachment
I do not know what to do, so i wonder could there any tool or script to easily just export and reimport text. Hope you can help
Sincere thanks
[sample.zip](https://github.com/bartlomiejduda/Tools/files/6911125/sample.zip)

**Comment by bartlomiejduda** [comment]
Hi, here is a simple tool for dumping all texts:
https://github.com/bartlomiejduda/Tools/blob/master/NEW%20Tools/Tom%20Clancy's%20Splinter%20Cell%20Conviction%20Mobile/Tom%20Clancy's%20Splinter%20Cell%20Conviction%20Mobile%20Tool.py

I don't usually make text importers, if i'm not intereested in the game, so you should probably ask someone ales for that.

Also, here is the result of extraction https://i.imgur.com/ZpeP8ei.png

**Comment by SakiMika** [comment]
> Hi, here is a simple tool for dumping all texts:
> https://github.com/bartlomiejduda/Tools/blob/master/NEW%20Tools/Tom%20Clancy's%20Splinter%20Cell%20Conviction%20Mobile/Tom%20Clancy's%20Splinter%20Cell%20Conviction%20Mobile%20Tool.py
> 
> I don't usually make text importers, if i'm not intereested in the game, so you should probably ask someone ales for that.
> 
> Also, here is the result of extraction https://i.imgur.com/ZpeP8ei.png

Thank you very much

**Comment by bartlomiejduda** [comment]
Ok, I've added import function in the tool linked above. Please check it, but I can't promise that it will work, because I haven't tested it in game.

**Comment by SakiMika** [comment]
As far as I know your tool does not support utf-8.
Yesterday, i tried to extract japanese and succeeded but today it failed
I need to extract the japanese file for String Replace, because the font of the game is too hard to edit

**Comment by bartlomiejduda** [comment]
My tool currently supports only utf16. Can you upload a sample with japanese text?

**Comment by SakiMika** [comment]
@bartlomiejduda 
[sample japanese.zip](https://github.com/bartlomiejduda/Tools/files/6915671/sample.japanese.zip)

**Comment by bartlomiejduda** [comment]
I've just tested and it worked fine for me without any changes to the code https://i.imgur.com/GXJLTQ2.png

**Comment by SakiMika** [comment]
> I've just tested it and it worked fine for me without any changes to the code https://i.imgur.com/GXJLTQ2.png

But it not work for me

<img src="https://i.ibb.co/qktNzBb/20210802-165604.jpg" alt="20210802-165604" border="0">

**Comment by luatsenpai** [comment]
![Screenshot_20220516-111905_Splinter Cell Conviction HD Free](https://user-images.githubusercontent.com/44133093/168520015-0156c462-3d16-4d18-acca-c6ad17e51842.jpg)
i tried it and it works
