### ISSUE TITLE
Can you write a tool to dump and reinsert text for Aot Wing of freedom?

### ISSUE THREAD

**Issue by fm39hz** [bartlomiejduda/Tools#7]
I'm trying to translate aot Wing of freedom, but the text file have the text length check which can't do automatic like pointer, can you help write a tool to make it?
here is the file format
this is number of text in the file
![image](https://user-images.githubusercontent.com/71458213/139527951-3d5fc99b-c1ce-42ed-98bf-e2839bf99ad6.png)
this is pointer point to the first text
![image](https://user-images.githubusercontent.com/71458213/139527985-2ca471d6-4a10-4d3c-91bc-f6c7c519db59.png)
and here is the size of that text
![image](https://user-images.githubusercontent.com/71458213/139527998-d7299a2e-1a2e-45dc-b755-47bd0be38e44.png)
that text respond to beyond information
![image](https://user-images.githubusercontent.com/71458213/139528018-884cdf88-0e26-4841-811d-9293b48e84ac.png)
added example file
[000013f6.zip](https://github.com/bartlomiejduda/Tools/files/7446222/000013f6.zip)

**Comment by bartlomiejduda** [comment]
Hi, it's ready. Try this script and let me know if it works for you :) 
https://github.com/bartlomiejduda/Tools/blob/master/NEW%20Tools/Attack%20on%20Titan%20Wings%20of%20Freedom/Aot_Wing_of_freedom_DAT_Tool.py

**Comment by fm39hz** [comment]
when i edit path then run, it throwback this
31-10-2021 07:27:58 Starting export_data...
Traceback (most recent call last):
  File "G:\Hienpham\vh\Project\AOTWoF\aot.py", line 133, in <module>
    main()
  File "G:\Hienpham\vh\Project\AOTWoF\aot.py", line 117, in main
    export_data(p_in_file_path, p_out_file_path)
  File "G:\Hienpham\vh\Project\AOTWoF\aot.py", line 36, in export_data
    os.makedirs(os.path.dirname(out_file_path))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'G:\\Hienpham\x0bh'

**Comment by bartlomiejduda** [comment]
Yeah, you should use double backslash "\\" in your paths to make it work.
I will simplify it in the template for the next tools.
